[build]
  publish = "/"
  command = "npm install && npm install --prefix netlify/functions"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  publish = "/"
  port = 3000
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[context.production]
  command = ""

[context.deploy-preview]
  command = ""

[context.branch-deploy]
  command = ""
